Repository softeerbootcamp-2nd/H3-UmochaRacer, pull requests merged in 2023-08, with the labels that each got.

#33 [FE] Hotfix 프로그래스 바 이벤트 추가
  frontend/src/component/progress/OptionItem.tsx
  frontend/src/component/progress/Progress.tsx
  frontend/src/component/progress/ProgressBar.tsx
Labels: 🔥 hotfix

#34 [FE] Dynamic Import 추가 및 환경 설정
  frontend/src/assets/images/main.png
  frontend/src/component/header/Header.tsx
  frontend/src/component/header/left/LeftMenu.tsx
  frontend/src/component/header/left/Logo.tsx
  frontend/src/component/header/left/ModeSelector.tsx
  frontend/src/component/header/right/CarMode.tsx
  frontend/src/component/header/right/Dictionary.tsx
  frontend/src/component/header/right/RightMenu.tsx
  frontend/src/component/progress/OptionItem.tsx
  frontend/src/component/progress/Progress.tsx
  frontend/src/component/progress/ProgressBar.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/Self.tsx
  frontend/src/style/global.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: 📝 feature, 🎨 FE

#52 [BE] Backend CI 구현
  .github/workflows/backend_test_integration.yml
Labels: 📝 feature, 🔐 BE, 🔨 Setting

#48 [FE] 옵션카드 컴포넌트 UI구현
  frontend/src/component/Content/SelectedOptionInfo/OptionCardList.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/left/OptionImage.tsx
  frontend/src/component/content/right/Footer.tsx
  frontend/src/component/content/right/OptionCardList.tsx
  frontend/src/component/content/right/OptionInfo.tsx
  frontend/src/component/content/right/card/DetailToggle.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/pages/Self.tsx
  frontend/src/style/theme.tsx
Labels: 📝 feature, 🎨 FE

#55 [FE] 폰트 관련 HOTFIX
  frontend/src/component/header/left/ModeSelector.tsx
  frontend/src/component/header/right/CarMode.tsx
  frontend/src/component/header/right/Dictionary.tsx
  frontend/src/component/progress/OptionItem.tsx
  frontend/src/component/progress/ProgressBar.tsx
Labels: 🔥 hotfix

#53 [BE] Backend CD 구현
  .github/workflows/backend_deploy.yml
  backend/Dockerfile
  backend/Dockerfile_compose
  backend/deploy_files/appspec.yml
  backend/deploy_files/deploy.sh
  docker-compose.yml
Labels: 📝 feature, 🔐 BE, 🔨 Setting

#58 [BE] FE CD 기능 추가
  .github/workflows/frontend_deploy.yml
  frontend/deploy_files/appspec.yml
  frontend/deploy_files/deploy.sh
Labels: 📝 feature, 🔐 BE, 🔨 Setting

#59 [BE] FE CD 기능 오류 수정
  .github/workflows/frontend_deploy.yml
  frontend/deploy_files/appspec.yml
  frontend/deploy_files/deploy.sh
Labels: 📝 feature, 🔐 BE, 🔥 hotfix

#47 [BE] 백카사전 키워드로 조회하는 api 구현
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/example/backend/BackendApplication.java
  backend/src/main/java/com/example/backend/domain/cardb/controller/CardbController.java
  backend/src/main/java/com/example/backend/domain/cardb/dto/CardbResponseDto.java
  backend/src/main/java/com/example/backend/domain/cardb/entity/Cardb.java
  backend/src/main/java/com/example/backend/domain/cardb/repository/CardbRepository.java
  backend/src/main/java/com/example/backend/domain/cardb/service/CardbService.java
  backend/src/main/java/com/example/backend/domain/global/dto/ResponseDto.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/static/docs/index.html
  backend/src/test/java/com/example/backend/domain/cardb/controller/CardbControllerTest.java
  backend/src/test/java/com/example/backend/domain/cardb/service/CardbServiceTest.java
  backend/src/test/java/com/example/backend/utils/AbstractRestDocsTest.java
  backend/src/test/java/com/example/backend/utils/ApiDocumentUtils.java
  backend/src/test/java/com/example/backend/utils/RestDocsConfiguration.java
Labels: 📝 feature, 🔐 BE

#40 [iOS] 공통 버튼 컴포넌트 (OhMyCarSetButton) 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Resource/Colors.swift
  iOS_H3/iOS_H3/Source/Presentation/OhMyCarSetButton.swift
  iOS_H3/iOS_H3/Source/Presentation/OhMyCarSetButtonViewController.swift
Labels: 📝 feature, 📱 iOS

#51 [iOS] 옵션 카드 버튼 컴포넌트 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Resource/Assets.xcassets/arrow_right_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/arrow_right_img.imageset/arrow_right_img.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/feedback_motion_face_first.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/feedback_motion_face_first.imageset/feedback_motion_face_first.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/feedback_motion_face_second.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/feedback_motion_face_second.imageset/feedback_motion_face_second.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/feedback_motion_good_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/feedback_motion_good_img.imageset/good_img.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/icon_check_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/icon_check_img.imageset/icon_check_img.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/icon_uncheck_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/icon_uncheck_img.imageset/icon_uncheck_img.svg
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/ColorViewOptionCardButton.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/ImageDisplayOptionButton.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/MoreInfoOptionButton.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/OptionCardButtonViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/OptionMotionView.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/TagListView.swift
Labels: 📝 feature, 📱 iOS

#61 [FE] 메인 페이지 UI 작성
  frontend/src/App.tsx
  frontend/src/assets/icons/more1.svg
  frontend/src/assets/icons/more2.svg
  frontend/src/component/common/icons.tsx
  frontend/src/component/main/MainContainer.tsx
  frontend/src/component/main/trimCard/TrimCard.tsx
  frontend/src/pages/Main.tsx
  frontend/src/style/theme.tsx
Labels: 📝 feature, 🎨 FE

#56 [iOS] 프로그레스 바 컴포넌트 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/CarMakingStep.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMakingProgressBar.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMakingProgressBarButton.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMakingProgressBarSpacingView.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMakingProgressBarViewController.swift
Labels: 📝 feature, 📱 iOS

#62 [FE] 하단모달 UI, 애니메이션 구현
  frontend/src/component/content/right/Footer.tsx
  frontend/src/component/content/right/OptionCardList.tsx
  frontend/src/component/content/right/OptionInfo.tsx
  frontend/src/component/content/right/card/DetailToggle.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/component/content/right/optioninfo/Estimate.tsx
  frontend/src/component/content/right/optioninfo/Modal.tsx
  frontend/src/component/content/right/optioninfo/estimate/Selection.tsx
Labels: 📝 feature, 🎨 FE

#70 [FE] 메인 페이지 일부 UI 구현 및 라우팅
  frontend/custom.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/arrow_right.svg
  frontend/src/assets/icons/index.ts
  frontend/src/assets/mocks/trim.json
  frontend/src/component/common/icons.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/component/header/Header.tsx
  frontend/src/component/main/MainContainer.tsx
  frontend/src/component/main/trimCard/TrimCard.tsx
  frontend/src/component/main/trimCard/trimDescription/TrimDescription.tsx
  frontend/src/main.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: 📝 feature, 🎨 FE

#67 [iOS] TwoOptionCardButtonView 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/Domain/Model/OptionCardInfo.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/ColorViewOptionCardButton.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/ImageDisplayOptionButton.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/MoreInfoOptionButton.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionCardButtonListViewable.swift
  iOS_H3/iOS_H3/Source/Presentation/TwoMoreInfoOptionCardButtonView.swift
  iOS_H3/iOS_H3/Source/Presentation/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3/Source/Presentation/TwoOptionCardButtonViewController.swift
Labels: 📝 feature, 📱 iOS

#66 [iOS] UI 타겟 컴포넌트 분리 및 Component Main VC 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3_UI/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS_H3/iOS_H3_UI/CarMakingProgressBar/CarMakingProgressBar.swift
  iOS_H3/iOS_H3_UI/CarMakingProgressBar/CarMakingProgressBarButton.swift
  iOS_H3/iOS_H3_UI/CarMakingProgressBar/CarMakingProgressBarSpacingView.swift
  iOS_H3/iOS_H3_UI/CarMakingProgressBar/CarMakingProgressBarViewController.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/Info.plist
  iOS_H3/iOS_H3_UI/OhMyCarSetButton/OhMyCarSetButton.swift
  iOS_H3/iOS_H3_UI/OhMyCarSetButton/OhMyCarSetButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardButtonListViewable.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoMoreInfoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/ColorViewOptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/ImageDisplayOptionButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/MoreInfoOptionButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionMotionView.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/TagListView.swift
  iOS_H3/iOS_H3_UI/SceneDelegate.swift
  iOS_H3/iOS_H3_UI/TitleBar/OhMyCarSetTitleBar.swift
  iOS_H3/iOS_H3_UI/TitleBar/OhMyCarSetTitleBarViewController.swift
  iOS_H3/iOS_H3_UI/ViewController.swift
Labels: 📝 feature, 📱 iOS, 🔨 Setting

#72 [FE] 옵션카드 마우스 이벤트(클릭, 호버)구현
  frontend/src/assets/images/gasoline.png
  frontend/src/assets/images/powertrain.png
  frontend/src/assets/mocks/powertrain.json
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/left/OptionImage.tsx
  frontend/src/component/content/right/OptionCardList.tsx
  frontend/src/component/content/right/OptionInfo.tsx
  frontend/src/component/content/right/card/DetailToggle.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/pages/Self.tsx
Labels: 📝 feature, 🎨 FE

#73 [FE] 메인 페이지의 상단 카드 뷰 구현
  frontend/index.html
  frontend/src/assets/images/le_blanc_option1.png
  frontend/src/assets/images/le_blanc_option2.png
  frontend/src/assets/images/le_blanc_option3.png
  frontend/src/assets/mocks/trim.json
  frontend/src/component/main/trimCard/TrimCard.tsx
  frontend/src/component/main/trimCard/trimDescription/TrimDescription.tsx
  frontend/src/component/main/trimCard/trimDescription/trimDescriptionDetail/DetailDescription.tsx
  frontend/src/component/main/trimCard/trimDescription/trimDescriptionDetail/DetailFeature.tsx
  frontend/src/component/main/trimCard/trimDescription/trimDescriptionDetail/TrimDescriptionDetail.tsx
  frontend/src/style/global.tsx
  frontend/tsconfig.json
Labels: 📝 feature, 🎨 FE

#75 [BE] 셀프모드 정보 조회 PR
  backend/src/main/java/com/example/backend/domain/cardb/controller/CardbController.java
  backend/src/main/java/com/example/backend/domain/cardb/entity/Cardb.java
  backend/src/main/java/com/example/backend/domain/cardb/service/CardbService.java
  backend/src/main/java/com/example/backend/domain/global/dto/ErrorResponse.java
  backend/src/main/java/com/example/backend/domain/global/dto/ResponseDto.java
  backend/src/main/java/com/example/backend/domain/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/example/backend/domain/global/exception/RestApiException.java
  backend/src/main/java/com/example/backend/domain/global/model/BaseInfo.java
  backend/src/main/java/com/example/backend/domain/global/model/enums/ErrorCode.java
  backend/src/main/java/com/example/backend/domain/information/controller/InformationController.java
  backend/src/main/java/com/example/backend/domain/information/dto/CarInformationResponse.java
  backend/src/main/java/com/example/backend/domain/information/dto/ColorInformationResponse.java
  backend/src/main/java/com/example/backend/domain/information/dto/CommonResponse.java
  backend/src/main/java/com/example/backend/domain/information/dto/InformationResponse.java
  backend/src/main/java/com/example/backend/domain/information/dto/OptionInformationResponse.java
  backend/src/main/java/com/example/backend/domain/information/mapper/InformationMapper.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/ExteriorColor.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/InteriorColor.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/Model.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/Trim.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/ExteriorColorRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/InteriorColorRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/ModelRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/TrimRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/AdditionalOption.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/Bodytype.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/DrivingSystem.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/Powertrain.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/AdditionalOptionRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/BodytypeRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/DrivingSystemRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/PowertrainRepository.java
  backend/src/main/java/com/example/backend/domain/information/service/InformationStrategyFactory.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/BodytypeStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/DrivingSystemStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/ExteriorColorStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/InformationStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/InteriorColorStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/OptionInformationStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/PowertrainStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/WheelStrategy.java
  backend/src/main/java/com/example/backend/domain/sale/entity/Sales.java
  backend/src/main/java/com/example/backend/domain/sale/entity/SalesOption.java
  backend/src/main/java/com/example/backend/domain/sale/entity/Tag.java
  backend/src/main/java/com/example/backend/domain/sale/entity/enums/Gender.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesOptionRepository.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesRepository.java
  backend/src/main/java/com/example/backend/domain/sale/repository/TagRepository.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/scheme.sql
  backend/src/test/java/com/example/backend/domain/cardb/controller/CardbControllerTest.java
  backend/src/test/java/com/example/backend/domain/cardb/service/CardbServiceTest.java
Labels: 📝 feature, 🔐 BE

#79 [FE] 메인 페이지 컴포넌트 분리
  frontend/src/component/main/MainContainer.tsx
  frontend/src/component/main/intro/IntroShowMore.tsx
  frontend/src/component/main/intro/IntroTitle.tsx
  frontend/src/component/main/intro/trimCard/TrimCard.tsx
  frontend/src/component/main/intro/trimCard/trimDescription/TrimDescription.tsx
  frontend/src/component/main/intro/trimCard/trimDescription/trimDescriptionDetail/DetailDescription.tsx
  frontend/src/component/main/intro/trimCard/trimDescription/trimDescriptionDetail/DetailFeature.tsx
  frontend/src/component/main/intro/trimCard/trimDescription/trimDescriptionDetail/TrimDescriptionDetail.tsx
  frontend/src/pages/Main.tsx
Labels: 📝 feature, 🎨 FE

#80 [FE] Context api 추가
  frontend/src/App.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/right/OptionCardList.tsx
  frontend/src/component/content/right/OptionInfo.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/component/progress/Progress.tsx
  frontend/src/provider/optionProvider.tsx
Labels: 📝 feature, 🎨 FE

#82 [BE] 내장색상 API 구현
  backend/src/main/java/com/example/backend/domain/information/controller/InformationController.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/InteriorColorRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/AdditionalOption.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/AdditionalOptionRepository.java
  backend/src/main/java/com/example/backend/domain/information/service/InformationStrategyFactory.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/InteriorColorStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/OptionInformationStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/WheelStrategy.java
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/scheme.sql
Labels: 📝 feature, 🔐 BE

#81 [iOS] OptionCardButton 서브클래스 기능을 상위 클래스로 통합하는 수정 작업
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/Domain/Model/OptionCardInfo.swift
  iOS_H3/iOS_H3/Source/Domain/Model/URColor.swift
  iOS_H3/iOS_H3/Source/Extensions/UIColor+.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/ColorViewOptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/ImageDisplayOptionButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/MoreInfoOptionButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionMotionView.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/TagListView.swift
Labels: 🏗️ refactoring, 📱 iOS

#84 [iOS] (셀프모드 컨텐츠 뷰 셀) CarMakingCollectionViewCell 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/Extensions/UILabel+.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingMultipleOptionCell.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingTwoOptionCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoMoreInfoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonViewController.swift
Labels: 📝 feature, 📱 iOS

#83 [FE] 카테고리 별 옵션카드 UI구현
  frontend/src/assets/images/20_darkwheel.png
  frontend/src/assets/images/20_darkwheel1.png
  frontend/src/assets/images/20inchwheel.png
  frontend/src/assets/images/2wd.png
  frontend/src/assets/images/4wd.png
  frontend/src/assets/images/7seats.png
  frontend/src/assets/images/8seats.png
  frontend/src/assets/images/alconbreak.png
  frontend/src/assets/images/black.png
  frontend/src/assets/images/blue.png
  frontend/src/assets/images/brown.png
  frontend/src/assets/images/grey.png
  frontend/src/assets/images/innerblack.png
  frontend/src/assets/images/innerblack1.png
  frontend/src/assets/images/innergrey.png
  frontend/src/assets/images/innergrey1.png
  frontend/src/assets/images/performance_logo.png
  frontend/src/assets/images/silver.png
  frontend/src/assets/images/white.png
  frontend/src/assets/mocks/bodytype.json
  frontend/src/assets/mocks/drivingsystem.json
  frontend/src/assets/mocks/exteriror-color.json
  frontend/src/assets/mocks/interior-color.json
  frontend/src/assets/mocks/powertrain.json
  frontend/src/assets/mocks/wheel.json
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/contentInterface.tsx
  frontend/src/component/content/left/OptionImage.tsx
  frontend/src/component/content/right/Footer.tsx
  frontend/src/component/content/right/OptionCardList.tsx
  frontend/src/component/content/right/OptionInfo.tsx
  frontend/src/component/content/right/card/DetailToggle.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/pages/Self.tsx
  frontend/src/provider/optionProvider.tsx
Labels: 📝 feature, 🎨 FE

#87 [BE] 상세 정보 & 피드백 반환 API 구현
  backend/src/main/java/com/example/backend/domain/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/example/backend/domain/global/model/enums/ErrorCode.java
  backend/src/main/java/com/example/backend/domain/information/controller/CommentController.java
  backend/src/main/java/com/example/backend/domain/information/controller/DetailController.java
  backend/src/main/java/com/example/backend/domain/information/dto/CommentResponse.java
  backend/src/main/java/com/example/backend/domain/information/dto/DetailResponse.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/ExteriorColorRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/InteriorColorRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/AdditionalOption.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/Bodytype.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/Detail.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/DrivingSystem.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/Powertrain.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/Wheel.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/AdditionalOptionRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/BodytypeRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/DetailRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/DrivingSystemRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/PowertrainRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/WheelRepository.java
  backend/src/main/java/com/example/backend/domain/information/service/DetailService.java
  backend/src/main/java/com/example/backend/domain/information/service/InformationStrategyFactory.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/BodytypeStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/DrivingSystemStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/ExteriorColorStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/InformationStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/InteriorColorStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/OptionInformationStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/PowertrainStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/WheelStrategy.java
  backend/src/main/resources/sql/data.sql
Labels: 📝 feature, 🔐 BE

#88 [BE] 트림 별로 외장색상 반환하는 API
  .github/workflows/backend_deploy.yml
  backend/src/main/java/com/example/backend/domain/global/model/BaseInfo.java
  backend/src/main/java/com/example/backend/domain/information/controller/InformationController.java
  backend/src/main/java/com/example/backend/domain/information/controller/IntroController.java
  backend/src/main/java/com/example/backend/domain/information/dto/IntroResponse.java
  backend/src/main/java/com/example/backend/domain/information/mapper/IntroSourceMapper.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/ExteriorColor.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/Trim.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/TrimExterior.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/TrimExteriorRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/TrimExteriorRowMapper.java
  backend/src/main/java/com/example/backend/domain/information/service/ColorService.java
  backend/src/main/resources/sql/data.sql
Labels: 📝 feature, 🔐 BE

#91 [BE] 메인화면에 들어갈 트림 별 내장색상 조회 API
  backend/src/main/java/com/example/backend/domain/information/controller/InformationController.java
  backend/src/main/java/com/example/backend/domain/information/controller/IntroController.java
  backend/src/main/java/com/example/backend/domain/information/dto/IntroResponse.java
  backend/src/main/java/com/example/backend/domain/information/dto/SimpleColorResponse.java
  backend/src/main/java/com/example/backend/domain/information/mapper/IntroSourceMapper.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/ExteriorColor.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/InteriorColor.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/TrimInterior.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/TrimInteriorRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/TrimInteriorRowMapper.java
  backend/src/main/java/com/example/backend/domain/information/service/ColorService.java
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/scheme.sql
Labels: 📝 feature, 🔐 BE

#103 [BE] InteriorColor FK문제로 API 안 되던 현상 수정 (먼저 머지 부탁)
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/InteriorColor.java
Labels: 🚨 bug, 🔐 BE

#90 [iOS] MultiOptionButtonView에 dot indicator 추가
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Resource/Colors.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/GuideModeOptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/SelfModeOptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
Labels: 📝 feature, 📱 iOS

#107 [BE] 카테고리 별로 추가옵션 반환하는 API 구현 (#78)
  backend/src/main/java/com/example/backend/domain/information/controller/DetailController.java
  backend/src/main/java/com/example/backend/domain/information/controller/InformationController.java
  backend/src/main/java/com/example/backend/domain/information/mapper/InformationMapper.java
  backend/src/main/java/com/example/backend/domain/information/model/option/entity/AdditionalOption.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/AdditionalOptionRepository.java
  backend/src/main/java/com/example/backend/domain/information/service/AdditionalOptionService.java
  backend/src/main/java/com/example/backend/domain/information/service/InformationStrategyFactory.java
Labels: 📝 feature, 🔐 BE

#109 [FE] 선택 피드백 제공기능 구현
  frontend/src/App.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/left/OptionImage.tsx
  frontend/src/component/content/right/Footer.tsx
  frontend/src/component/content/right/OptionCardList.tsx
  frontend/src/component/content/right/OptionInfo.tsx
  frontend/src/component/content/right/card/FeedBack.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/component/loding/Bottom.tsx
  frontend/src/component/loding/LoadingAnimation.tsx
  frontend/src/component/loding/ProgressIndicator.tsx
  frontend/src/pages/Loading.tsx
Labels: 📝 feature, 🎨 FE

#96 [iOS] CarMakingContentView 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Source/Extensions/UIImageView+.swift
  iOS_H3/iOS_H3/Source/Extensions/UIView+.swift
  iOS_H3/iOS_H3/Source/ImageCacheManager.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingMultipleOptionCell.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingTwoOptionCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentViewController.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/PageSection.swift
  iOS_H3/iOS_H3_UI/CarMakingProgressBar/CarMakingProgressBar.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
Labels: 📝 feature, 📱 iOS

#113 [BE] WebMvcConfigurer로 CORS 설정
  backend/src/main/java/com/example/backend/domain/global/config/WebConfig.java
Labels: 📝 feature, 🔐 BE

#100 [iOS] 하단 모달창 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/Extensions/Int+.swift
  iOS_H3/iOS_H3_UI/Assets.xcassets/temp_estimateSummary.imageset/Contents.json
  iOS_H3/iOS_H3_UI/Assets.xcassets/temp_estimateSummary.imageset/temp_estimateSummary.png
  iOS_H3/iOS_H3_UI/BottomModalView.swift
  iOS_H3/iOS_H3_UI/BottomModalViewController.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/EstimateSummaryView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
Labels: 📝 feature, 📱 iOS

#125 [iOS] 네트워크서비스 구현
  iOS_H3/NetworkLayerTest/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS_H3/NetworkLayerTest/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS_H3/NetworkLayerTest/Assets.xcassets/Contents.json
  iOS_H3/NetworkLayerTest/Base.lproj/LaunchScreen.storyboard
  iOS_H3/NetworkLayerTest/Info.plist
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/App/SceneDelegate.swift
  iOS_H3/iOS_H3/Source/Extensions/URL+.swift
  iOS_H3/iOS_H3/Source/Extensions/URLRequest+.swift
  iOS_H3/iOS_H3/Source/Network/EndPoint.swift
  iOS_H3/iOS_H3/Source/Network/NetworkError.swift
  iOS_H3/iOS_H3/Source/Network/NetworkService.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonViewController.swift
Labels: 📝 feature, 📱 iOS

#129 [iOS] CarMakingMode 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/CarMakingMode.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButtonViewController.swift
Labels: 📝 feature, 📱 iOS

#136 [FE] 메인 페이지 API 연결
  frontend/.env
  frontend/src/api/fetchData.ts
  frontend/src/component/hooks/useFetch.ts
  frontend/src/component/hooks/useScroll.ts
  frontend/src/component/main/MainContainer.tsx
  frontend/src/component/main/modelOption/default/ModelDefaultOption.tsx
  frontend/src/component/main/modelOption/default/ModelOptionDetail.tsx
  frontend/src/component/main/modelOption/inner/ModelInnerOption.tsx
  frontend/src/component/main/modelOption/inner/ModelOptionDetail.tsx
  frontend/src/component/main/modelOption/outer/ModelOptionDetail.tsx
  frontend/src/component/main/modelOption/outer/ModelOuterOption.tsx
  frontend/src/component/util/sortData.ts
Labels: 📝 feature, 🎨 FE

#126 [FE] 팝업 UI 구현
  frontend/src/assets/icons/change.svg
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/sad.svg
  frontend/src/assets/images/powerTrainChange.png
  frontend/src/component/main/MainContainer.tsx
  frontend/src/component/modal/Modal.tsx
  frontend/src/component/modal/ModalLayout.tsx
  frontend/src/component/modal/exit/ExitModal.tsx
  frontend/src/component/modal/modeChange/GuideChangeModal.tsx
  frontend/src/component/modal/modeChange/SelfChangeModal.tsx
  frontend/src/component/modal/modelChange/ModelChangeModal.tsx
  frontend/src/component/modal/powerTrainChange/PowerTrainModal.tsx
Labels: 📝 feature, 🎨 FE

#138 [iOS] 내차만들기 ViewController 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/App/SceneDelegate.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3_UI/BottomModalView.swift
  iOS_H3/iOS_H3_UI/BottomModalViewController.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentViewController.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/PageSection.swift
  iOS_H3/iOS_H3_UI/CarMakingProgressBar/CarMakingProgressBar.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/TitleBar/OhMyCarSetTitleBar.swift
  iOS_H3/iOS_H3_UI/TitleBar/OhMyCarSetTitleBarViewController.swift
Labels: 📝 feature, 📱 iOS

#134 [BE] 초기 견적값 반환 API
  backend/src/main/java/com/example/backend/domain/intro/controller/IntroController.java
  backend/src/main/java/com/example/backend/domain/intro/dto/EstimateResponse.java
  backend/src/main/java/com/example/backend/domain/intro/service/InitialService.java
Labels: 📝 feature, 🔐 BE

#130 [BE] 테스트코드 (API 연결 작업하는데 서버 터질까봐 PR로 올립니다)
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/com/example/backend/domain/global/config/WebConfig.java
  backend/src/main/resources/static/docs/index.html
  backend/src/main/resources/static/docs/rest-docs.yaml
  backend/src/main/resources/static/rest-docs.html
  backend/src/test/java/com/example/backend/AbstractRestDocsTest.java
  backend/src/test/java/com/example/backend/BackendApplicationTest.java
  backend/src/test/java/com/example/backend/domain/cardb/controller/CardbControllerTest.java
  backend/src/test/java/com/example/backend/domain/cardb/service/CardbServiceTest.java
  backend/src/test/java/com/example/backend/domain/information/controller/AdditonalOptionInformationControllerTest.java
  backend/src/test/java/com/example/backend/domain/information/controller/CarInformationControllerTest.java
  backend/src/test/java/com/example/backend/domain/information/controller/ColorInformationControllerTest.java
  backend/src/test/java/com/example/backend/domain/information/service/strategy/AbstractStrategyTest.java
  backend/src/test/java/com/example/backend/domain/information/service/strategy/ExteriorColorServiceTest.java
  backend/src/test/java/com/example/backend/domain/information/service/strategy/InteriorColorServiceTest.java
  backend/src/test/java/com/example/backend/domain/information/service/strategy/PowertrainSerivceTest.java
  backend/src/test/java/com/example/backend/domain/intro/controller/IntroControllerTest.java
  backend/src/test/java/com/example/backend/utils/AbstractRestDocsTest.java
Labels: 🔐 BE

#140 [FE] 견적뽑기 완료 컴포넌트 구현
  frontend/src/App.tsx
  frontend/src/component/common/EstimateList.tsx
  frontend/src/component/common/estimate/Estimate.tsx
  frontend/src/component/common/estimate/Selection.tsx
  frontend/src/component/common/estimateInterface.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/totalestimate/EstimateContent.tsx
  frontend/src/component/content/totalestimate/TotalEstimate.tsx
  frontend/src/component/content/totalestimate/estimatecontent/Bottom.tsx
  frontend/src/component/content/totalestimate/estimatecontent/EstimateHeader.tsx
  frontend/src/component/content/totalestimate/estimatecontent/FireWork.tsx
  frontend/src/component/content/totalestimate/estimatecontent/Middle.tsx
  frontend/src/component/content/totalestimate/estimatecontent/Top.tsx
  frontend/src/component/content/totalestimate/estimatecontent/bottom/DetailEstimate.tsx
  frontend/src/component/loding/Bottom.tsx
  frontend/src/component/loding/LoadingAnimation.tsx
  frontend/src/pages/Loading.tsx
  frontend/src/provider/optionProvider.tsx
Labels: 📝 feature, 🎨 FE

#143 [FE] 팝업 이벤트 연동 구현
  frontend/.env
  frontend/src/component/header/left/Logo.tsx
  frontend/src/component/header/left/ModeSelector.tsx
  frontend/src/component/header/right/CarMode.tsx
  frontend/src/component/main/MainContainer.tsx
  frontend/src/component/modal/ModalLayout.tsx
  frontend/src/component/modal/exit/ExitModal.tsx
  frontend/src/component/modal/modeChange/GuideChangeModal.tsx
Labels: 📝 feature, 🎨 FE

#149 [FE] 옵션 데이터 api 연결
  frontend/src/App.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/contentInterface.tsx
  frontend/src/component/content/left/OptionImage.tsx
  frontend/src/component/content/right/OptionInfo.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/component/main/modelOption/default/ModelDefaultOption.tsx
  frontend/src/component/util/getCategory.ts
  frontend/src/pages/Self.tsx
  frontend/src/provider/selectedOptionProvider.tsx
Labels: 📝 feature, 🎨 FE

#133 [iOS] CarInfoRepository 구현 및 관련 Response DTO 정의
  iOS_H3/DTO/CarInfo/AdditionalOptionResponse.swift
  iOS_H3/DTO/CarInfo/BodyTypeResponse.swift
  iOS_H3/DTO/CarInfo/CarInfoRepository.swift
  iOS_H3/DTO/CarInfo/DrivingSystemResponse.swift
  iOS_H3/DTO/CarInfo/ExteriorColorResponse.swift
  iOS_H3/DTO/CarInfo/InteriorColorResponse.swift
  iOS_H3/DTO/CarInfo/PowertrainResponse.swift
  iOS_H3/DTO/CarInfo/SingleExteriorColorResponse.swift
  iOS_H3/DTO/CarInfo/WheelResponse.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Source/ConstantKey.swift
  iOS_H3/iOS_H3/Source/Extensions/CarInfoRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/Network/CarInfoEndpoint.swift
Labels: 📝 feature, 📱 iOS

#144 [iOS] 옵션 선택 리스트뷰 컴포넌트 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Resource/Assets.xcassets/image_mode_button_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/image_mode_button_img.imageset/image_mode_button_img.svg
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeView.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeViewController.swift
Labels: 📝 feature, 📱 iOS

#157 [BE] (셀프모드) 옵션 선택률 API 일부 구현
  backend/src/main/java/com/example/backend/domain/global/model/enums/ResultCode.java
  backend/src/main/java/com/example/backend/domain/global/utils/StringUtils.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/ExteriorColorRepository.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/ExteriorColorService.java
  backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java
  backend/src/main/java/com/example/backend/domain/sale/dto/SalesSummaryResponse.java
  backend/src/main/java/com/example/backend/domain/sale/entity/OptionSalesSummary.java
  backend/src/main/java/com/example/backend/domain/sale/entity/SalesOptions.java
  backend/src/main/java/com/example/backend/domain/sale/entity/SalesSummary.java
  backend/src/main/java/com/example/backend/domain/sale/mapper/SelectionRatioRowMapper.java
  backend/src/main/java/com/example/backend/domain/sale/mapper/SummaryMapper.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesOptionRepository.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesOptionsRepository.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesRepository.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/sale/service/OptionSaleRatioServiceImpl.java
  backend/src/main/java/com/example/backend/domain/sale/service/RatioService.java
  backend/src/main/java/com/example/backend/domain/sale/service/SaleRatioServiceImpl.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelfModeServiceFactory.java
  backend/src/test/java/com/example/backend/domain/information/service/strategy/ExteriorColorServiceTest.java
Labels: 📝 feature, 🔐 BE

#159 [BE] (셀프모드) 옵션 선택률 API 완성
  backend/src/main/java/com/example/backend/domain/global/utils/StringUtils.java
  backend/src/main/java/com/example/backend/domain/information/model/car/entity/ExteriorColor.java
  backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesRepository.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelfModeServiceFactory.java
  backend/src/main/java/com/example/backend/domain/sale/service/VehicleSpecificationSaleRatioServiceImpl.java
  backend/src/main/java/com/example/backend/domain/sale/service/VehicleTypeSaleRatioServiceImpl.java
Labels: 📝 feature, 🔐 BE

#161 [FE] DetailBox에 API오류 수정
  frontend/src/component/content/right/OptionCardList.tsx
  frontend/src/component/content/right/OptionInfo.tsx
Labels: 🚨 bug, 🎨 FE

#162 [FE] Context 사용으로 중복되는 props 제거
  frontend/src/App.tsx
  frontend/src/component/common/DetilBox.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/right/Footer.tsx
  frontend/src/component/content/right/OptionCardList.tsx
  frontend/src/component/content/right/OptionInfo.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/provider/selectedOptionProvider.tsx
  frontend/src/provider/tempOptionProvider.tsx
Labels: 🚨 bug, 📝 feature, 🎨 FE

#165 [BE] 태그 목록 반환하는 API
  backend/src/main/java/com/example/backend/domain/guide/controller/TagController.java
  backend/src/main/java/com/example/backend/domain/guide/dto/TagInformationResponse.java
  backend/src/main/java/com/example/backend/domain/guide/dto/TagListResponse.java
  backend/src/main/java/com/example/backend/domain/guide/entity/Tag.java
  backend/src/main/java/com/example/backend/domain/guide/mapper/TagInformationMapper.java
  backend/src/main/java/com/example/backend/domain/guide/repository/TagRepository.java
  backend/src/main/java/com/example/backend/domain/guide/service/TagService.java
  backend/src/main/java/com/example/backend/domain/sale/entity/Sales.java
Labels: 📝 feature, 🔐 BE

#160 [BE]선택률 Request Uri 수정
  backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java
Labels: 🚨 bug, 🔐 BE

#168 [BE] 하위 옵션이 있는 추가 옵션의 상세 정보 API 오류 수정
  backend/src/main/java/com/example/backend/domain/information/controller/DetailController.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/AdditionalOptionRepository.java
  backend/src/main/java/com/example/backend/domain/information/service/AdditionalOptionService.java
  backend/src/main/java/com/example/backend/domain/information/service/DetailService.java
Labels: 🚨 bug, 🔐 BE

#170 [iOS] 내차만들기 옵션 선택시 배너 이미지 표시
  iOS_H3/iOS_H3/Source/Domain/Model/OptionCardInfo.swift
  iOS_H3/iOS_H3/Source/Domain/Model/URColor.swift
  iOS_H3/iOS_H3/Source/Extensions/UIImageView+.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardButtonListViewable.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeView.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeViewController.swift
Labels: 🚨 bug, 📱 iOS

#172 [iOS] SelfModeUsecase 구현(Part1)
  iOS_H3/DTO/CarInfo/APIResponse.swift
  iOS_H3/DTO/CarInfo/AdditionalOptionResponse.swift
  iOS_H3/DTO/CarInfo/BodyTypeResponse.swift
  iOS_H3/DTO/CarInfo/CarInfoRepository.swift
  iOS_H3/DTO/CarInfo/CarOptionData.swift
  iOS_H3/DTO/CarInfo/DrivingSystemResponse.swift
  iOS_H3/DTO/CarInfo/EstimateElementData.swift
  iOS_H3/DTO/CarInfo/ExteriorColorResponse.swift
  iOS_H3/DTO/CarInfo/InteriorColorResponse.swift
  iOS_H3/DTO/CarInfo/PowertrainResponse.swift
  iOS_H3/DTO/CarInfo/SelfModeUsecase.swift
  iOS_H3/DTO/CarInfo/SingleExteriorColorResponse.swift
  iOS_H3/DTO/CarInfo/WheelResponse.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Info.plist
  iOS_H3/iOS_H3/Source/App/SceneDelegate.swift
  iOS_H3/iOS_H3/Source/ConstantKey.swift
  iOS_H3/iOS_H3/Source/Domain/Model/EstimateSummary.swift
  iOS_H3/iOS_H3/Source/Domain/Model/URColor.swift
  iOS_H3/iOS_H3/Source/Extensions/CarInfoRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/Network/CarInfoEndpoint.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3_UI/OptionListView/SelfModeUsecaseProtocol.swift
Labels: 📝 feature, 📱 iOS

#180 [iOS] 옵션 선택 단계에 카테고리 탭바 추가 & 리스트 모드 변경 기능 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Resource/Assets.xcassets/list_mode_button.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/list_mode_button.imageset/list_mode_button.svg
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3_UI/BottomModalView/BottomModalView.swift
  iOS_H3/iOS_H3_UI/BottomModalView/BottomModalViewController.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingOptionSelectStepCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentViewController.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/PageSection.swift
  iOS_H3/iOS_H3_UI/EstimateSummaryView/EstimateSummaryView.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeView.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeViewController.swift
Labels: 🚨 bug, 📱 iOS

#179 [iOS] 선택완료 버튼 클릭시 피드백 모션 보여주기
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingOptionSelectStepCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardButtonListViewable.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionMotionView.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeView.swift
Labels: 📝 feature, 📱 iOS

#182 [iOS] IntroRepository 구현 (Repository Layer)
  iOS_H3/DTO/CarInfo/CarInfoRepository.swift
  iOS_H3/DTO/CarInfo/EstimateElementData.swift
  iOS_H3/DTO/CarInfo/SelfModeUsecase.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Source/App/SceneDelegate.swift
  iOS_H3/iOS_H3/Source/Extensions/CarInfoRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/Network/CarInfoEndpoint.swift
  iOS_H3/iOS_H3/Source/Network/IntroEndpoint.swift
  iOS_H3/iOS_H3/Source/Network/IntroRepository.swift
  iOS_H3/iOS_H3/Source/Network/IntroRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3_UI/OptionListView/SelfModeUsecaseProtocol.swift
Labels: 📝 feature, 📱 iOS

#176 [BE] 자동차 부품 아이디로 단일 조회 하는 API
  backend/src/main/java/com/example/backend/domain/cardb/service/CardbService.java
  backend/src/main/java/com/example/backend/domain/global/model/enums/ResultCode.java
  backend/src/main/java/com/example/backend/domain/information/controller/InformationController.java
  backend/src/main/java/com/example/backend/domain/information/dto/CommentResponse.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/ExteriorColorRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/car/repository/InteriorColorRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/BodytypeRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/DrivingSystemRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/PowertrainRepository.java
  backend/src/main/java/com/example/backend/domain/information/model/option/repository/WheelRepository.java
  backend/src/main/java/com/example/backend/domain/information/service/AdditionalOptionService.java
  backend/src/main/java/com/example/backend/domain/information/service/DetailService.java
  backend/src/main/java/com/example/backend/domain/information/service/InformationStrategyFactory.java
  backend/src/main/java/com/example/backend/domain/information/service/InteriorColorService.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/BodytypeService.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/DrivingSystemService.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/ExteriorColorService.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/InformationStrategy.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/PowertrainService.java
  backend/src/main/java/com/example/backend/domain/information/service/strategy/WheelService.java
  backend/src/test/java/com/example/backend/domain/information/controller/ColorInformationControllerTest.java
  backend/src/test/java/com/example/backend/domain/information/service/strategy/InteriorColorServiceTest.java
Labels: 📝 feature, 🔐 BE

#190 [FE] 자세히 보기 내용 cache화 및 최적화
  frontend/src/component/common/DetilBox.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/right/card/DetailToggle.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
Labels: 📝 feature, 🎨 FE

#185 [BE] 태그 선택률이 80% 이상 비슷한 사용자의 각 옵션 선택률 API
  backend/src/main/java/com/example/backend/domain/global/model/enums/ResultCode.java
  backend/src/main/java/com/example/backend/domain/global/utils/StringUtils.java
  backend/src/main/java/com/example/backend/domain/guide/dto/EstimateRequest.java
  backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersService.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersServiceImpl.java
  backend/src/main/resources/sql/selectCountWithSimilarUsers.sql
Labels: 📝 feature, 🔐 BE

#194 [iOS] 백카사전 단어 찾기 로직 구현
  iOS_H3/DTO/CarInfo/CarInfoRepository.swift
  iOS_H3/DTO/CarInfo/CarOptionData.swift
  iOS_H3/DTO/CarInfo/SelfModeUsecase.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/Domain/Model/CarMakingStepInfoEntity.swift
  iOS_H3/iOS_H3/Source/Domain/Model/OptionCardInfoEntity.swift
  iOS_H3/iOS_H3/Source/Extensions/CarInfoRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/Extensions/String+.swift
  iOS_H3/iOS_H3/Source/Network/IntroRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3/Source/Presentation/Model/CarMakingStepInfo.swift
  iOS_H3/iOS_H3/Source/Presentation/Model/OptionCardInfo.swift
  iOS_H3/iOS_H3/Source/URString.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionListView/SelfModeUsecaseProtocol.swift
Labels: 📝 feature, 📱 iOS

#199 [iOS] 백카(car)사전 on - 용어 하이라이팅 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_off_img.imageset/dictionary_img.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_on_img.imageset/dictionary_on_img.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_selected_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_selected_img.imageset/dictionary_selected_img.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_unselected_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_unselected_img.imageset/dictionary_unselected.svg
  iOS_H3/iOS_H3/Source/DictionaryString.swift
  iOS_H3/iOS_H3/Source/Extensions/UILabel+.swift
  iOS_H3/iOS_H3/Source/TextEffectManager.swift
  iOS_H3/iOS_H3_UI/URLabel/URLabel.swift
Labels: 📝 feature, 📱 iOS

#205 [BE] guide_mode와 유사 사용자 구매율 API merge conflict 해결
  backend/src/main/java/com/example/backend/domain/guide/dto/EstimateRequest.java
  backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersService.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersServiceImpl.java
Labels: 🚨 bug, 🔐 BE

#206 [BE] 진짜 마지막요ㅠㅠ 배포용 브랜치로 PR
  backend/src/main/java/com/example/backend/domain/guide/dto/EstimateRequest.java
  backend/src/main/java/com/example/backend/domain/sale/controller/SaleRatioController.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersService.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersServiceImpl.java
Labels: 🚨 bug, 🔐 BE

#186 [iOS] 견적 요약 화면 구현
  iOS_H3/DTO/CarInfo/CarOptionData.swift
  iOS_H3/DTO/CarInfo/EstimateElementData.swift
  iOS_H3/DTO/CarInfo/SelfModeUsecase.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/CarMakingCategory.swift
  iOS_H3/iOS_H3/Source/Domain/Model/EstimateSummary.swift
  iOS_H3/iOS_H3/Source/Extensions/Int+.swift
  iOS_H3/iOS_H3/Source/Extensions/String+.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3_UI/BottomModalView/BottomModalView.swift
  iOS_H3/iOS_H3_UI/EstimateSummaryView/EstimateSummaryCell.swift
  iOS_H3/iOS_H3_UI/EstimateSummaryView/EstimateSummaryHeaderView.swift
  iOS_H3/iOS_H3_UI/EstimateSummaryView/EstimateSummaryView.swift
Labels: 📝 feature, 📱 iOS

#189 [FE] 가이드 모드 사용자 정보 선택 플로우 UI구현
  frontend/src/component/common/EstimateList.tsx
  frontend/src/component/common/estimate/Estimate.tsx
  frontend/src/component/common/estimate/Selection.tsx
  frontend/src/component/content/right/Footer.tsx
  frontend/src/component/content/right/card/FeedBack.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/component/content/right/optioninfo/Modal.tsx
  frontend/src/component/content/totalestimate/EstimateContent.tsx
  frontend/src/component/content/totalestimate/estimatecontent/Bottom.tsx
  frontend/src/component/content/totalestimate/estimatecontent/FireWork.tsx
  frontend/src/component/content/totalestimate/estimatecontent/Middle.tsx
  frontend/src/component/content/totalestimate/estimatecontent/bottom/DetailEstimate.tsx
  frontend/src/component/guidecontent/GuidData.tsx
  frontend/src/component/guidecontent/GuideContent.tsx
  frontend/src/component/guidecontent/GuideEstimate.tsx
  frontend/src/component/guidecontent/SelectFlow.tsx
  frontend/src/component/guidecontent/guideestimate/EstimateContent.tsx
  frontend/src/component/guidecontent/selectflow/CardList.tsx
  frontend/src/component/guidecontent/selectflow/GridList.tsx
  frontend/src/pages/Guide.tsx
  frontend/src/provider/selectedOptionProvider.tsx
Labels: 📝 feature, 🎨 FE

#208 [BE] 가이드 모드 API 로직 수정 및 쿼리 최적화 적용
  backend/build.gradle
  backend/src/main/java/com/example/backend/domain/global/config/RedisConfig.java
  backend/src/main/java/com/example/backend/domain/guide/service/CarRecommendationServiceImpl.java
  backend/src/main/java/com/example/backend/domain/guide/service/OptionRecommendationHandler.java
  backend/src/main/java/com/example/backend/domain/guide/service/OptionRecommendationHandlerImpl.java
  backend/src/main/java/com/example/backend/domain/sale/mapper/SummaryMapper.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesOptionsRepository.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/sale/repository/TagRatioTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/sale/service/OptionSaleRatioServiceImpl.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersServiceImpl.java
  backend/src/main/resources/application-dev.yml
Labels: 📝 feature, 🔐 BE

#188 [iOS] 자세히 보기 뷰 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Source/Domain/Model/CarMakingStepInfoEntity.swift
  iOS_H3/iOS_H3/Source/Domain/Model/DetailInfo.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.xib
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/NoImageDetailPopupViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/NoImageDetailPopupViewController.xib
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewModel/DetailPopupUsecaseProtocol.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewModel/DetailPopupViewModel.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/PagingControlView/PagingControlView.swift
Labels: 📝 feature, 📱 iOS

#210 [iOS] 옵션 선택 단계 카테고리 변경 기능 구현
  iOS_H3/DTO/CarInfo/CarInfoRepository.swift
  iOS_H3/DTO/CarInfo/SelfModeUsecase.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/App/SceneDelegate.swift
  iOS_H3/iOS_H3/Source/Data/Repository/CarInfoMockRepository.swift
  iOS_H3/iOS_H3/Source/Extensions/CarInfoRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/OptionCategoryType.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingOptionSelectStepCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCategoryTabbar/OptionCategoryTabBar.swift
  iOS_H3/iOS_H3_UI/OptionListView/SelfModeUsecaseProtocol.swift
Labels: 📝 feature, 📱 iOS

#222 [iOS] 백카(car)사전 on - 용어 선택 & 번역 텍스트 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_off_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_off_img.imageset/dictionary_off_img.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_on_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/dictionary_on_img.imageset/dictionary_on_img.svg
  iOS_H3/iOS_H3/Source/Data/Repository/CarInfoMockRepository.swift
  iOS_H3/iOS_H3/Source/Domain/UseCase/DictionaryOptionUsecase.swift
  iOS_H3/iOS_H3/Source/Extensions/UILabel+.swift
  iOS_H3/iOS_H3/Source/Extensions/UIView+.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3/Source/Presentation/Detail/ViewModel/DictionaryUsecaseProtocol.swift
  iOS_H3/iOS_H3/Source/Presentation/Detail/ViewModel/TextBoxViewModel.swift
  iOS_H3/iOS_H3/Source/TextEffectManager.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentViewController.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/TextBox/TextBoxView.swift
  iOS_H3/iOS_H3_UI/TextBox/TextBoxViewController.swift
  iOS_H3/iOS_H3_UI/TextBox/TopAlignedLabel.swift
  iOS_H3/iOS_H3_UI/TitleBar/OhMyCarSetTitleBar.swift
  iOS_H3/iOS_H3_UI/URLabel/URLabel.swift
Labels: 📝 feature, 📱 iOS

#228 [FE] 모드 변경 팝업 구현
  frontend/src/assets/icons/Fix.svg
  frontend/src/assets/icons/index.ts
  frontend/src/component/header/left/ModeSelector.tsx
  frontend/src/component/modal/Modal.tsx
  frontend/src/component/modal/modeChange/ModeChangeModal.tsx
  frontend/src/component/util/getTitleByPath.ts
  frontend/src/provider/modalProvider.tsx
  frontend/src/style/theme.tsx
Labels: 📝 feature, 🎨 FE

#232 [FE] 선택 옵션 이미지 세부사항 보이기 구현
  frontend/src/App.tsx
  frontend/src/component/common/DetailSelectedBox.tsx
  frontend/src/component/content/SelectedOptionContent.tsx
  frontend/src/component/content/left/AdditionalOptionImage.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/provider/tempImageProvider.tsx
Labels: 📝 feature, 🎨 FE

#236 [FE] 자잘한 수정 및 배포 수정
  .github/workflows/frontend_deploy.yml
  frontend/src/component/common/EstimateList.tsx
  frontend/src/component/common/Warning.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/right/Footer.tsx
  frontend/src/component/content/right/OptionCardList.tsx
  frontend/src/provider/optionProvider.tsx
  frontend/src/provider/selectedOptionProvider.tsx
  frontend/src/provider/tempOptionProvider.tsx
Labels: 📝 feature

#237 [FE] 옵션카드 모드 별 스타일 변경
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/contentInterface.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/component/content/right/card/Tag.tsx
Labels: 📝 feature, 🎨 FE

#244 [FE] 선택옵션 가이드 모드 구현
  frontend/src/component/common/EstimateList.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/left/OptionImage.tsx
  frontend/src/component/content/right/SelectedOptionCardList.tsx
  frontend/src/component/content/right/card/Tag.tsx
  frontend/src/component/guidecontent/GuideContent.tsx
Labels: 📝 feature, 🎨 FE

#219 [iOS] 선택 시 피드백 기능 구현
  iOS_H3/DTO/CarInfo/CarInfoRepository.swift
  iOS_H3/DTO/CarInfo/SelfModeUsecase.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/Data/Repository/CarInfoMockRepository.swift
  iOS_H3/iOS_H3/Source/Domain/Model/FeedbackCommentEntity.swift
  iOS_H3/iOS_H3/Source/Extensions/CarInfoRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/Network/CommentEndpoint.swift
  iOS_H3/iOS_H3/Source/Network/FeedbackCommentData.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3/Source/Presentation/Model/FeedbackComment.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingOptionSelectStepCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardButtonListViewable.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionMotionView.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeView.swift
  iOS_H3/iOS_H3_UI/OptionListView/SelfModeUsecaseProtocol.swift
Labels: 📝 feature, 📱 iOS

#226 [iOS] 자세히보기(Detail) Repository 구현 (파워트레인, 구동방식, 바디타임, 휠, 추가옵션 상세 정보)
  iOS_H3/DTO/CarInfo/SelfModeUsecase.swift
  iOS_H3/DTO/Detail/DetailOptionData.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Source/DetailRepository.swift
  iOS_H3/iOS_H3/Source/DetailRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/Network/DetailEndPoint.swift
Labels: 📝 feature, 📱 iOS

#235 [iOS] 메인화면 임시 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Resource/Assets.xcassets/main_guideMode.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/main_guideMode.imageset/main_guideMode.png
  iOS_H3/iOS_H3/Resource/Assets.xcassets/main_leBlanc.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/main_leBlanc.imageset/main_leBlanc.png
  iOS_H3/iOS_H3/Source/App/SceneDelegate.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/MainViewController.swift
  iOS_H3/iOS_H3/Source/TrimCategory.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/TrimListBar.swift
  iOS_H3/iOS_H3_UI/TrimListBarButton.swift
  iOS_H3/iOS_H3_UI/TrimListBarViewController.swift
Labels: 📝 feature, 📱 iOS

#243 [iOS] 백카사전 usecase, repository 구현
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/Data/DTO/DictionaryDescriptionData.swift
  iOS_H3/iOS_H3/Source/Data/Repository/DictionaryRepository.swift
  iOS_H3/iOS_H3/Source/Data/Repository/Protocol/DictionaryRepositoryProtocol.swift
  iOS_H3/iOS_H3/Source/Domain/Model/DictionaryDescription.swift
  iOS_H3/iOS_H3/Source/Domain/UseCase/DictionaryOptionUsecase.swift
  iOS_H3/iOS_H3/Source/Domain/UseCase/DictionaryUsecase.swift
  iOS_H3/iOS_H3/Source/Network/DictionaryEndpoint.swift
  iOS_H3/iOS_H3/Source/Presentation/Detail/ViewModel/DictionaryUsecaseProtocol.swift
  iOS_H3/iOS_H3/Source/Presentation/Detail/ViewModel/TextBoxViewModel.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
Labels: 📝 feature, 📱 iOS

#245 [iOS] 자세히보기 Detail Usecase 구현(파워트레인, 구동방식, 바디타입, 휠, 추가옵션 상세정보)
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Source/Domain/Model/DetailInfo.swift
  iOS_H3/iOS_H3/Source/Domain/Model/MockDetailOptionEntity.swift
  iOS_H3/iOS_H3/Source/Domain/UseCase/DetailPopupUsecase.swift
  iOS_H3/iOS_H3/Source/Extensions/String+.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/MainViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/Model/CarMakingStepInfo.swift
  iOS_H3/iOS_H3/Source/Presentation/Model/DetailOptionInfo.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.xib
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/NoImageDetailPopupViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/NoImageDetailPopupViewController.xib
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewModel/DetailPopupUsecaseProtocol.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewModel/DetailPopupViewModel.swift
  iOS_H3/iOS_H3/Source/Presentation/ViewController.swift
  iOS_H3/iOS_H3/Source/TextEffectManager.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingOptionSelectStepCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/MultiOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardButtonListViewable.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeView.swift
  iOS_H3/iOS_H3_UI/OptionListView/OptionListModeViewController.swift
  iOS_H3/iOS_H3_UI/TextBox/URLabel/TextBoxView.swift
  iOS_H3/iOS_H3_UI/TextBox/URLabel/URLabel.swift
Labels: 📝 feature, 📱 iOS

#254 [iOS] 선택완료 연속 클릭 이슈 수정, 옵션 선택 단계에서는 피드백 모션 실행 X
  iOS_H3/DTO/CarInfo/SelfModeUsecase.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionListView/SelfModeUsecaseProtocol.swift
Labels: 🚨 bug, 📱 iOS

#257 [FE] 자잘한 QA 및 불필요한 렌더링 수정
  frontend/src/component/content/Content.tsx
  frontend/src/component/content/right/SelectedOptionInfo.tsx
  frontend/src/component/content/right/card/OptionCard.tsx
  frontend/src/component/guidecontent/guideestimate/EstimateContent.tsx
  frontend/src/provider/modalProvider.tsx
Labels: 📝 feature, 🎨 FE

#256 [BE] (가이드모드) 나와 비슷한 사용자 선택률 API에 해당하는 데이터 없을 때 예외처리
  backend/src/main/java/com/example/backend/domain/sale/mapper/SummaryMapper.java
  backend/src/main/java/com/example/backend/domain/sale/repository/SalesTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/sale/repository/TagRatioTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/sale/service/SelectionRatioWithSimilarUsersServiceImpl.java
Labels: 🚨 bug, 🔐 BE

#249 [iOS] 팝업뷰 구현하기
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Resource/Assets.xcassets/change_popup_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/change_popup_img.imageset/change_popup_img.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/exit_popup_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/exit_popup_img.imageset/exit_popup_img.svg
  iOS_H3/iOS_H3/Resource/Assets.xcassets/tools_fill_img.imageset/Contents.json
  iOS_H3/iOS_H3/Resource/Assets.xcassets/tools_fill_img.imageset/tools_fill_img.svg
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/Popup/ExitPopup/ExitPopupViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/Popup/ExitPopup/ExitPopupViewController.xib
  iOS_H3/iOS_H3/Source/Presentation/Popup/ModeChangePopup/ModeChangeButton.swift
  iOS_H3/iOS_H3/Source/Presentation/Popup/ModeChangePopup/ModeChangeCheckPopup/ModeChangeCheckPopupViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/Popup/ModeChangePopup/ModeChangeCheckPopup/ModeChangeCheckPopupViewController.xib
  iOS_H3/iOS_H3/Source/Presentation/Popup/ModeChangePopup/ModeChangePopupViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/Popup/ModeChangePopup/ModeChangePopupViewController.xib
  iOS_H3/iOS_H3/Source/Presentation/Popup/ModelChangePopup/ModelChangePopupViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/Popup/ModelChangePopup/ModelChangePopupViewController.xib
Labels: 📝 feature, 📱 iOS

#251 [iOS] 견적 갱신 버그를 수정한다
  iOS_H3/DTO/CarInfo/SelfModeUsecase.swift
  iOS_H3/iOS_H3/Source/Extensions/String+.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3_UI/BottomModalView/BottomModalView.swift
Labels: 🚨 bug, 📱 iOS

#258 [iOS] 백카사전 관련 여러 이슈 수정
  iOS_H3/iOS_H3/Source/Data/Repository/CarInfoMockRepository.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewModel/CarMakingViewModel.swift
  iOS_H3/iOS_H3/Source/Presentation/MainViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/OptionDetail/ViewController/ImageDetailPopupViewController.swift
  iOS_H3/iOS_H3/Source/TextEffectManager.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingCollectionViewCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/TwoOptionCardButtonView/TwoOptionCardButtonView.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/TitleBar/OhMyCarSetTitleBar.swift
Labels: 🚨 bug, 📱 iOS

#260 [iOS] 견적 완료화면 구현
  iOS_H3/DTO/CarInfo/CarOptionData.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS_H3/iOS_H3/Source/Data/Repository/CarInfoMockRepository.swift
  iOS_H3/iOS_H3/Source/Domain/Model/OptionCardInfoEntity.swift
  iOS_H3/iOS_H3/Source/Extensions/UIView+.swift
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3/Source/Presentation/Model/OptionCardInfo.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingEstimateCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentView.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/PageSection.swift
  iOS_H3/iOS_H3_UI/OhMyCarSetButton/OhMyCarSetButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButonListView/OptionCardCell.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButton.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButtonViewController.swift
Labels: 📝 feature, 📱 iOS

#262 [iOS] 백카사전 usecase 연결
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/Domain/UseCase/DictionaryOptionUsecase.swift
  iOS_H3/iOS_H3/Source/Domain/UseCase/DictionaryUsecase.swift
  iOS_H3/iOS_H3/Source/Presentation/Detail/ViewModel/TextBoxViewModel.swift
  iOS_H3/iOS_H3_UI/ComponentMainViewController.swift
  iOS_H3/iOS_H3_UI/TextBox/TextBoxViewController.swift
  iOS_H3/iOS_H3_UI/TextBox/URLabel/URLabel.swift
Labels: 📝 feature, 📱 iOS

#266 [iOS] 각종 오류 수정
  iOS_H3/DTO/Detail/DetailOptionData.swift
  iOS_H3/iOS_H3.xcodeproj/project.pbxproj
  iOS_H3/iOS_H3/Source/Presentation/CarMaking/ViewController/CarMakingViewController.swift
  iOS_H3/iOS_H3_UI/CarMakingCollectionViewCell/CarMakingEstimateCell.swift
  iOS_H3/iOS_H3_UI/CarMakingContentView/CarMakingContentViewController.swift
  iOS_H3/iOS_H3_UI/OptionCardButton/OptionCardButtonViewController.swift
Labels: 📱 iOS, 🔥 hotfix
